# Generated by Django 2.0.1 on 2018-01-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_remove_emaillog_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_set_for_emaillog', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
