# Generated by Django 2.0.1 on 2018-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180108_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='bcc',
            field=models.TextField(help_text='A comma separated list of bcc', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='cc',
            field=models.TextField(help_text='A comma separated list of cc', null=True),
        ),
    ]
